OLTP:
  drivername: "ODBC Driver 17 for SQL Server"
  dbname: 
  user: 
  password: 
  host: localhost
  port: 1433

OLAP:
  drivername: "ODBC Driver 17 for SQL Server"
  dbname: 
  user: 
  password: 
  host: localhost
  port: 1433

LOAD_DIMENSIONS:
  True
